---

- name: Change pool member status
  hosts: all
  connection: local
  gather_facts: false
  collections:
    - f5networks.f5_modules

  vars_files:
    - vault

  vars:
    provider:
      server: f51.example.com
      server_port: 443
      user: admin
      password: "{{ password }}"
      validate_certs: no

    # Edit node_state to either enabled or forced_offline
    node_state: forced_offline
    partition_name: Common
    pool_name: /Common/webapps_pool
    node_host: node1
    node_port: 443


  tasks:  
  - name: Changing node state
    bigip_pool_member:
      state: "{{ node_state }}"
      partition: "{{partition_name}}"
      pool: "{{ pool_name }}"
      address: "{{ node_host }}"
      port: "{{node_port}}"
      provider: "{{ provider }}"
    delegate_to: localhost
  
  - name: Syncing config between F5 units
    bigip_configsync_action:
      device_group: device-group-a-failover
      sync_device_to_group: yes
      provider: "{{ provider }}"
    delegate_to: localhost

  - name: Summary
    ansible.builtin.debug:
      msg: 
      - "{{ pool_name }}/{{ node_host }}:{{node_port}} status has changed to {{ node_state }}." 
