---

- name: Change pool member state
  hosts: all
  connection: local
  gather_facts: false
  collections:
    - f5networks.f5_modules

  vars_files:
    - vault

  vars:
    provider:
      server: f51
      server_port: 443
      user: admin
      password: "{{ password }}"
      validate_certs: no

    # Edit node_state to either enabled or forced_offline
    node_state: forced_offline
    partition_name: Common
    pool_name: /Common/webapps_pool
    node_host: node1
    node_port: 443

  roles:
    - change_node_status
