---

- name: F5 node change
  hosts: all
  connection: local
  gather_facts: false
  collections:
    - f5networks.f5_modules

  vars_files:
    - vault

  vars:
    provider:
      server: 10.1.114.12
      server_port: 443
      user: admin
      password: "{{ f5san }}"
      validate_certs: no

    # Edit the following values only
    ### https://docs.ansible.com/ansible/latest/collections/f5networks/f5_modules/bigip_pool_member_module.html
    node_state: enabled
    partition_name: ITS-Middleware_SecureApps
    pool_name: /ITS-Middleware_SecureApps/appstst.its_https_pool
    node_host: appstst01
    node_port: 8441


  tasks:  
  - name: Changing node state
    bigip_pool_member:
      state: "{{ node_state }}"
      partition: "{{partition_name}}"
      pool: "{{ pool_name }}"
      address: "{{ node_host }}"
      port: "{{node_port}}"
      provider: "{{ provider }}"
    delegate_to: localhost
  
  - name: Syncing config between F5 units
    bigip_configsync_action:
      device_group: device-group-a-failover
      sync_device_to_group: yes
      provider: "{{ provider }}"
    delegate_to: localhost

  - name: Summary
    ansible.builtin.debug:
      msg: 
      - "{{ pool_name }}/{{ node_host }}:{{node_port}} status has changed to {{ node_state }}." 