---

- name: Upgrade F5
  hosts: all
  gather_facts: false
  collections:
    - f5networks.f5_modules


  vars_files:
    - vault

  vars:
    provider:
      server: 10.1.114.11
      server_port: 443
      user: admin
      password: "{{ f5san }}"
      validate_certs: no

  vars_prompt:
    - name: Choose version to install
      prompt: "Type ISO version (i.e. 15.1.3-0.0.11)"
      private: no

  tasks:

    # Pre upgrade tasks
    - name: "Task 1: Check failover state"
      shell: tmsh show sys failover | awk '{print $2}'
      register: failover_state

    - block:
      - name: "Task 2: Check running config"
        command: tmsh load sys config verify
   
      - name: "Task 3: Waiting for configuration to load"
        wait_for:
          timeout: 30
        delegate_to: localhost

      - name: "Task 4: Get current time"
        command: date "+%Y_%m_%d_%H%M"
        register: date

      - name: "Task 5: Download a new UCS"
        bigip_ucs_fetch:
          src: "{{ inventory_hostname + '-' + date.stdout +  '.ucs' }}"
          dest: "{{ '/apps/f5_config_backup/' + inventory_hostname + '-' + date.stdout +  '.ucs' }}"
          provider: "{{ provider }}"
        delegate_to: localhost

      - name: "Task 6: Download a qkview"
        bigip_qkview:
          asm_request_log: yes
          exclude:
            - audit
            - secure
          dest: "{{ '/apps/f5_qkview/' + inventory_hostname + '-' + date.stdout +  '.qkview' }}"
          provider: "{{ provider }}"
        delegate_to: localhost

      - name: "Task 7: Upload image to F5"
        bigip_software_image:
         image: "{{ '/apps/f5/iso/BIGIP-' + version  + '.iso' }}"
         provider: "{{ provider }}"
        delegate_to: localhost
      
      - name: "Task 8: Wait For Confirmation"
        pause:
          prompt: "Press a key to continue upgrading F5..."


      # Upgrade
      - name: "Task 9: Install BIG-IP"
        bigip_software_install:
          image: "{{ 'BIGIP-' + version  + '.iso' }}"
          state: activated
          volume: "HD1.3"                                     
          provider: "{{ provider }}"
        delegate_to: localhost
        async: 45
        poll: 0

      - name: "Task 10: Waiting for update to complete"
        wait_for:
          timeout: 1200
        delegate_to: localhost


      # Post upgrade tasks
      - name: "Task 11: Upload daily backup script"
        ansible.builtin.copy:
          src: /apps/f5_scripts/bigip_ltm_11_backup.sh
          dest: /etc/cron.daily/bigip_ltm_11_backup.sh
          mode: '0700'

      - name: "Task 12: Upload monthly iHealth script"
        ansible.builtin.copy:
          src: /apps/f5_scripts/remote_qkview_script
          dest: /etc/cron.monthly/remote_qkview_script
          mode: '0700'
  
      - name: "Task 13: Run daily backup script"
        shell: /etc/cron.daily/bigip_ltm_11_backup.sh

      - name: "Task 14: Run monthly iHealth script"
        shell: /etc/cron.monthly/remote_qkview_script
      
      - name: "Task 15: Configure Anacron"
        ansible.builtin.lineinfile:
          path: /var/spool/anacron/cron.monthly
          line: date "+%Y%m%d"


      when: failover_state.stdout  == 'standby'